config/version.php, core/Api.php, core/AppException.php, core/BaseModel.php, core/Config.php, core/Controller.php, core/Functions.php, core/Json.php, core/Language.php, core/Loader.php, core/Log.php, core/Menu.php, core/Request.php, core/Response.php, core/Script.php, core/Session.php, core/User.php, core/Viewer.php, core/WebUI.php, core/errorhandler.php
=> Changed license -1-

language/en_us/Basic.php, language/en_us/Install.php, language/en_us/Users.php, language/pl_pl/Basic.php, language/pl_pl/Install.php, language/pl_pl/Users.php, layouts/Default/modules/Base/fieldtypes/Boolean.tpl, layouts/Default/modules/Base/fieldtypes/Date.tpl, layouts/Default/modules/Base/fieldtypes/Double.tpl, layouts/Default/modules/Base/fieldtypes/Email.tpl, layouts/Default/modules/Base/fieldtypes/Integer.tpl, layouts/Default/modules/Base/fieldtypes/Multipicklist.tpl, layouts/Default/modules/Base/fieldtypes/Owner.tpl, layouts/Default/modules/Base/fieldtypes/Percentage.tpl, layouts/Default/modules/Base/fieldtypes/Phone.tpl, layouts/Default/modules/Base/fieldtypes/Picklist.tpl, layouts/Default/modules/Base/fieldtypes/Reference.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceLink.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceProcess.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceSubProcess.tpl
=> Changed license -2-

layouts/Default/modules/Base/ActionMenu.tpl, layouts/Default/modules/Base/Body.tpl, layouts/Default/modules/Base/BodyContent.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/BodyLeft.tpl, layouts/Default/modules/Base/BodyRight.tpl, layouts/Default/modules/Base/BreadCrumbs.tpl, layouts/Default/modules/Base/ButtonLink.tpl, layouts/Default/modules/Base/DebugApi.tpl, layouts/Default/modules/Base/DetailView.tpl, layouts/Default/modules/Base/EditView.tpl, layouts/Default/modules/Base/Footer.tpl, layouts/Default/modules/Base/Header.tpl, layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Base/ListViewActions.tpl, layouts/Default/modules/Base/fieldtypes/SharedOwner.tpl, layouts/Default/modules/Base/fieldtypes/String.tpl, layouts/Default/modules/Base/fieldtypes/Text.tpl, layouts/Default/modules/Base/fieldtypes/Time.tpl, layouts/Default/modules/Base/fieldtypes/Url.tpl
=> Changed license -3-

layouts/Default/modules/Base/Log.tpl, layouts/Default/modules/Base/Pagination.tpl, layouts/Default/modules/Base/SearchMenu.tpl, layouts/Default/modules/Install/InstallPostProcess.tpl, layouts/Default/modules/Install/InstallPreProcess.tpl, layouts/Default/modules/Install/InstallStep1.tpl, layouts/Default/modules/Install/InstallStep2.tpl, layouts/Default/modules/Users/Body.tpl, layouts/Default/modules/Users/BodyRight.tpl, layouts/Default/modules/Users/Login.tpl, modules/Base/Action/Base.php, modules/Base/Action/ChangeCompany.php, modules/Base/Action/Delete.php, modules/Base/Action/Save.php, modules/Base/FieldTypes/BaseField.php, modules/Base/FieldTypes/BooleanField.php, modules/Base/FieldTypes/DateField.php, modules/Base/FieldTypes/MultipicklistField.php, modules/Base/Model/DetailView.php, modules/Base/Model/Field.php
=> Changed license -4-

index.php, modules/Base/Model/Module.php, modules/Base/Model/Record.php, modules/Base/View/DetailView.php, modules/Base/View/EditView.php, modules/Base/View/Index.php, modules/Base/View/ListView.php, modules/Install/Action/Install.php, modules/Install/Model/Install.php, modules/Install/View/Install.php, modules/Users/Action/Login.php, modules/Users/Action/Logout.php, modules/Users/View/Login.php, public/index.php, public/layouts/Default/modules/Base/resources/EditView.js, public/layouts/Default/modules/Base/resources/Header.js, public/layouts/Default/modules/Base/resources/ListView.js, public/layouts/Default/modules/Install/resources/Install.js, public/layouts/Default/resources/app.js, tests/bootstrap.php, tests/phpunit/00_Install.php, tests/phpunit/01_Integration.php, tests/times.php
=> Changed license -5-

composer.json
Added lib guzzlehttp/guzzle to composer
=> Added lib guzzlehttp/guzzle

layouts/Default/modules/Base/ActionMenu.tpl, layouts/Default/modules/Base/Body.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/BodyLeft.tpl, layouts/Default/modules/Base/DebugApi.tpl, layouts/Default/modules/Base/DetailView.tpl, layouts/Default/modules/Base/EditView.tpl, layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Base/ListViewActions.tpl, layouts/Default/modules/Base/SearchMenu.tpl, layouts/Default/modules/Base/fieldtypes/Multipicklist.tpl, layouts/Default/modules/Install/InstallPreProcess.tpl, layouts/Default/modules/Install/InstallStep1.tpl, layouts/Default/modules/Install/InstallStep2.tpl, layouts/Default/modules/Users/Body.tpl, layouts/Default/modules/Users/Login.tpl, public_html/layouts/Default/modules/Base/resources/Header.js, public_html/layouts/Default/modules/Base/resources/ListView.js, public_html/layouts/Default/resources/app.js, public_html/layouts/Default/resources/helper.js
=> Changed class hide to d-none

composer.json, index.php, public_html/index.php
Change namespace from YF\Core to App part 2
=> Change namespace from YF\Core to App part 2

layouts/Default/modules/Base/ActionMenu.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/DebugApi.tpl, layouts/Default/modules/Base/DetailView.tpl, layouts/Default/modules/Base/EditView.tpl, layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Users/Login.tpl
Changed class panel-body to card-body
=> Changed class panel-body to card-body

layouts/Default/modules/Base/ActionMenu.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/BodyLeft.tpl, layouts/Default/modules/Base/DetailView.tpl, layouts/Default/modules/Base/EditView.tpl, layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Base/fieldtypes/Date.tpl, layouts/Default/modules/Base/fieldtypes/Percentage.tpl, layouts/Default/modules/Base/fieldtypes/Reference.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceLink.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceProcess.tpl, layouts/Default/modules/Base/fieldtypes/ReferenceSubProcess.tpl, layouts/Default/modules/Base/fieldtypes/Time.tpl, layouts/Default/modules/Install/InstallStep2.tpl, layouts/Default/modules/Users/Login.tpl, public_html/layouts/Default/resources/Field.js, public_html/layouts/Default/skins/basic/styles.css
Changed class input-group-addon to input-group-append
=> Mass changed of class name.

app/Api.php, app/AppException.php, app/Config.php, app/Functions.php, config/Config.php, layouts/Default/modules/Users/Login.tpl
Possibility of blocking the language selection by the user.
=> Possibility of blocking the language selection by the user.

app/Controller/View.php, app/Json.php, layouts/Default/modules/Products/Tree/Product.tpl, layouts/Default/modules/Products/Tree/Tree.tpl, modules/Base/Model/ListView.php, modules/Base/View/ListView.php, modules/Products/View/Tree.php, public_html/layouts/Default/modules/Products/resources/Tree.js
Adding the product tree view.
Addition of the record list model.
Refactoring the code.
=> Adding the product tree view.

app/Controller/Action.php, app/Controller/Base.php, app/Controller/ExposeMethodTrait.php, app/Controller/Modal.php, app/Controller/View.php, app/WebUI.php, config/Config.php, layouts/Default/modules/Install/InstallStep1.tpl, modules/Base/Action/ChangeCompany.php, modules/Base/Action/Delete.php, modules/Base/Action/Save.php, modules/Base/View/DetailView.php, modules/Base/View/EditView.php, modules/Base/View/ListView.php, modules/Base/View/RecordList.php, modules/Install/Action/Install.php, modules/Install/Model/Install.php, modules/Install/View/Install.php, modules/Products/View/ShoppingCart.php, modules/Products/View/Tree.php, modules/Users/Action/Login.php, modules/Users/Action/Logout.php, modules/Users/View/Login.php, public_html/layouts/Default/modules/Install/resources/Install.js, tests/phpunit/01_Integration.php
Refactoring the code. Removing the "Request" from the methods parameter.
=> Refactoring the code. Removing the "Request" from the methods parameter.

layouts/Default/modules/Base/Body.tpl, layouts/Default/modules/Base/BodyLeft.tpl, layouts/Default/modules/Base/Menu/Label.tpl, layouts/Default/modules/Base/Menu/Module.tpl, layouts/Default/modules/Base/Menu/SubMenu.tpl, modules/Base/Model/Menu.php, public_html/layouts/Default/resources/app.js, public_html/layouts/Default/skins/basic/layout/_Base.scss, public_html/layouts/Default/skins/basic/layout/_Menu.scss
=> Corrected menu

layouts/Default/modules/Base/Menu/HomeIcon.tpl, layouts/Default/modules/Products/ProceedToCheckout/Product.tpl, layouts/Default/modules/Products/ProceedToCheckout/Summary.tpl, layouts/Default/modules/Products/ShoppingCart/Product.tpl, layouts/Default/modules/Products/ShoppingCart/ShoppingCart.tpl, layouts/Default/modules/Products/ShoppingCart/Summary.tpl, layouts/Default/modules/Products/Tree/Category.tpl, layouts/Default/modules/Products/Tree/Product.tpl, layouts/Default/modules/Products/Tree/Search.tpl, layouts/Default/modules/Products/Tree/Tree.tpl, layouts/Default/modules/Products/Tree/TreePreProcess.tpl, public_html/layouts/Default/skins/basic/_Utilities.scss, public_html/layouts/Default/skins/basic/views/_Product.scss
=> Corected view module Product

layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Base/ListViewActions.tpl
=> Corrected button action

layouts/Default/modules/Base/Detail/DetailView.tpl, layouts/Default/modules/Base/EditView.tpl
=> Corrected details view and edit view

languages/en-US/Basic.json, languages/en-US/Products.json, layouts/Default/modules/Base/Menu/HomeIcon.tpl, layouts/Default/modules/Base/Menu/Label.tpl, layouts/Default/modules/Base/Menu/Module.tpl, layouts/Default/modules/Base/Menu/Shortcut.tpl, layouts/Default/modules/Products/Preview/Preview.tpl, modules/Products/View/Preview.php
=> Corrected view product

layouts/Default/modules/Base/Pagination.tpl, layouts/Default/modules/Products/ShoppingCart/ShoppingCart.tpl, modules/Products/View/ShoppingCart.php, public_html/layouts/Default/modules/Products/resources/Tree.js, public_html/layouts/Default/skins/basic/_Utilities.scss, public_html/layouts/Default/skins/basic/layout/_Base.scss
=> Corrected Page Navigation

public_html/layouts/Default/modules/Base/resources/Header.js, public_html/layouts/Default/skins/basic/layout/_Header.scss
=> Corrected view the history

public_html/layouts/Default/resources/app.js, public_html/layouts/Default/resources/helper.js
=> Corrected notifications

layouts/Default/modules/Base/Body.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/BodyLeft.tpl, layouts/Default/modules/Base/ListView.tpl, layouts/Default/modules/Products/Tree/Product.tpl, layouts/Default/modules/Products/Tree/TreePreProcess.tpl, public_html/layouts/Default/resources/app.js, public_html/layouts/Default/skins/basic/layout/_Menu.scss, public_html/layouts/Default/skins/basic/views/_Product.scss
=> Corrected view responsive in Product

layouts/Default/modules/Base/Detail/DetailView.tpl
=> Improved responsiveness of the detailed view

layouts/Default/modules/Base/EditView.tpl
=> Improved responsiveness of the edit view

app/Payments/Transfer.php, config/Payments/Transfer.php, languages/en-US/Products.json, layouts/Default/modules/Products/ShoppingCart/Payments/CashOnDelivery.tpl, layouts/Default/modules/Products/ShoppingCart/Payments/DotPay.tpl, layouts/Default/modules/Products/ShoppingCart/Payments/Redsys.tpl, layouts/Default/modules/Products/ShoppingCart/Payments/Transfer.tpl, layouts/Default/modules/Products/ShoppingCart/ShoppingCart.tpl, layouts/Default/modules/Products/ShoppingCart/Summary.tpl, public_html/layouts/Default/modules/Products/resources/ShoppingCart.js
=> Improved payments selection and shipping cart view

app/Payments/AbstractPayments.php, app/Payments/CashOnDelivery.php, app/Payments/Dotpay.php, app/Payments/Redsys.php, app/Payments/Transfer.php, layouts/Default/modules/Base/Body.tpl, layouts/Default/modules/Base/BodyContent.tpl, layouts/Default/modules/Base/BodyHeader.tpl, layouts/Default/modules/Base/Pagination.tpl, layouts/Default/modules/Products/ProceedToCheckout/Payments/CashOnDelivery.tpl, layouts/Default/modules/Products/ProceedToCheckout/Payments/DotPay.tpl, layouts/Default/modules/Products/ProceedToCheckout/Payments/Redsys.tpl, layouts/Default/modules/Products/ProceedToCheckout/Payments/Transfer.tpl, layouts/Default/modules/Products/ProceedToCheckout/ProceedToCheckout.tpl, layouts/Default/modules/Products/ProceedToCheckout/Summary.tpl, layouts/Default/modules/Products/ShoppingCart/ShoppingCart.tpl, layouts/Default/modules/Products/ShoppingCart/Summary.tpl, public_html/layouts/Default/modules/Products/resources/ShoppingCart.js, public_html/layouts/Default/skins/basic/Main.scss, public_html/layouts/Default/skins/basic/_Components.scss, public_html/layouts/Default/skins/basic/_Libraries.scss, public_html/layouts/Default/skins/basic/layout/_Base.scss, public_html/layouts/Default/skins/basic/layout/_Footer.scss, public_html/layouts/Default/skins/basic/layout/_Header.scss, public_html/layouts/Default/skins/basic/layout/_Menu.scss, public_html/layouts/Default/skins/basic/views/_Product.scss
=> Improved shipping card and checkout views

payments.php
Improving the status of payments
=> Improving the status of payments

app/Api.php, app/Log.php, modules/Products/View/Preview.php
Optimization of communication between CRM
=> Optimization of communication between CRM

public_html/layouts/resources/icons/yfm.css
=> Added icons yfm

public_html/layouts/Default/modules/Install/resources/Install.js, public_html/layouts/Default/modules/Products/resources/Preview.js, public_html/layouts/Default/modules/Products/resources/ProceedToCheckout.js, public_html/layouts/Default/modules/Products/resources/ShoppingCart.js, public_html/layouts/Default/modules/Products/resources/Tree.js, public_html/layouts/Default/resources/app.js
=> Corrected PNotify

app/Installer/Credits.php, layouts/Default/modules/YetiForce/Credits.tpl, layouts/Default/modules/YetiForce/LibraryLicense.tpl, layouts/Default/modules/YetiForce/LibraryMoreInfo.tpl, public_html/layouts/Default/modules/YetiForce/resources/Credits.js
Add Credits module with library view
=> Add Credits module with library view

app/Controller/View.php, app/Installer/Credits.php, app/Language.php, config/Config.php, languages/en-US/Basic.json, languages/en-US/YetiForce.json, layouts/Default/modules/Base/Footer.tpl, layouts/Default/modules/YetiForce/Credits.tpl, layouts/Default/modules/YetiForce/LibraryLicense.tpl, layouts/Default/modules/YetiForce/LibraryMoreInfo.tpl, modules/YetiForce/View/Credits.php, modules/YetiForce/View/LibraryLicense.php, modules/YetiForce/View/LibraryMoreInfo.php, public_html/layouts/Default/modules/YetiForce/resources/Credits.js, public_html/layouts/resources/app.js
=> Credits module

config/Config.php, config/Inventory.php
Standardization of comments in configuration files
=> Standardization of comments in configuration files

app/Language.php, app/Utils.php, config/Config.php
=> Modification of getAllLanguages function

modules/Home/View/Dashboard.php, modules/Products/View/Tree.php
Corrected declaration of the function
=> Corrected declaration of the function

layouts/Default/modules/Base/BodyHeader.tpl
=> Corrected body header

languages/en-US/Install.json, layouts/Default/modules/Base/Footer.tpl, layouts/Default/modules/Install/InstallStep1.tpl
=> Corrected Footer and select

layouts/Default/modules/Base/fieldtypes/Multipicklist.tpl, layouts/Default/modules/Base/fieldtypes/Owner.tpl, layouts/Default/modules/Base/fieldtypes/Picklist.tpl, layouts/Default/modules/Base/fieldtypes/Reference.tpl, layouts/Default/modules/Base/fieldtypes/SharedOwner.tpl, layouts/Default/modules/Install/InstallStep1.tpl, layouts/Default/modules/Products/ShoppingCart/ShoppingCart.tpl
=> Corrected select

config/Inventory.php, layouts/Default/modules/Base/Detail/DetailView.tpl, modules/Base/View/DetailView.php, public_html/layouts/Default/skins/basic/_Components.scss
=> Corrected detail view

app/Controller/View.php
=> Corrected on/off min files

layouts/Default/modules/Base/DebugApi.tpl
=> Corrected debug api card header.

layouts/Default/modules/Base/ListViewActions.tpl
=> Added a background to the action buttons.

app/Controller/View.php
Corrected url to input mask library
=> Corrected url to input mask library

layouts/Default/modules/Base/fieldtypes/Date.tpl, layouts/Default/modules/Base/fieldtypes/Percentage.tpl, layouts/Default/modules/Base/fieldtypes/Reference.tpl, layouts/Default/modules/Base/fieldtypes/Time.tpl, layouts/Default/modules/Base/fieldtypes/Tree.tpl, public_html/layouts/Default/skins/basic/_Libraries.scss
=> Unified of fields according to the appearance of crm

layouts/Default/modules/Base/ListView.tpl, public_html/layouts/Default/skins/basic/_Components.scss, public_html/layouts/Default/skins/basic/_Libraries.scss
=> Adjusted Header and pagination

modules/Products/Model/TreeView.php, modules/Products/View/ShoppingCart.php, modules/Products/View/Tree.php
Corrected instance declarations
=> Corrected instance declarations

layouts/Default/modules/Base/EditView.tpl, layouts/Default/modules/Base/fieldtypes/Boolean.tpl, modules/Base/FieldTypes/BaseField.php, public_html/layouts/Default/skins/basic/_Checkbox.scss
=> Unified type boolean according to crm

app/Controller/Modal.php, layouts/Default/modules/Base/Modal/Header.tpl, layouts/Default/modules/Base/RecordList/RecordList.tpl, modules/Base/View/Pdf.php, modules/Base/View/RecordList.php, modules/YetiForce/View/LibraryLicense.php, modules/YetiForce/View/LibraryMoreInfo.php, public_html/layouts/Default/skins/basic/Main.scss, public_html/layouts/Default/skins/basic/layout/_Modal.scss
=> Corrected size modal and added icon

layouts/Default/modules/Base/fieldtypes/Double.tpl, public_html/layouts/resources/validator/FieldValidator.js
=> Unified uitype Doubel

layouts/Default/modules/Base/fieldtypes/Email.tpl, modules/Base/FieldTypes/BaseField.php, public_html/layouts/Default/skins/basic/Main.scss
=> Corrected uitype Email

layouts/Default/modules/Base/BodyLeft.tpl, modules/Base/Model/DetailView.php
Corrected logo and added label in edit button
=> Corrected logo and added label in edit button

layouts/Default/modules/Base/Footer.tpl, modules/Base/Model/DetailView.php
Added label in buttons and changed color text in footer
=> Added label in buttons and changed color text in footer

languages/en-US/Basic.json
=> Added translation

languages/en-US/Basic.json, layouts/Default/modules/Base/Edit/Field/Integer.tpl, layouts/Default/modules/Base/fieldtypes/Integer.tpl, public_html/layouts/resources/validator/FieldValidator.js
=> Unified uitype Integer

layouts/Default/modules/Base/Edit/Field/Url.tpl, layouts/Default/modules/Base/fieldtypes/Url.tpl, public_html/layouts/resources/validator/FieldValidator.js
=> Unified Url field

config/Config.php
=> Added variable to config

layouts/Default/modules/Base/Edit/Field/Currency.tpl, modules/Base/FieldTypes/BaseField.php, public_html/layouts/resources/validator/FieldValidator.js
=> Unified Currency field

modules/Base/FieldTypes/ReferenceExtendField.php, modules/Base/FieldTypes/ReferenceLinkField.php, modules/Base/FieldTypes/ReferenceProcessField.php
Added function getTemplateName
=> Added function getTemplateName

layouts/Default/modules/Base/Edit/Field/String.tpl, layouts/Default/modules/Base/fieldtypes/String.tpl
=> Unified String field

modules/Base/FieldTypes/SharedOwnerField.php
=> Corrected Shared owner field

public_html/layouts/Default/modules/Base/resources/EditView.js, public_html/layouts/Default/modules/Base/resources/Header.js, public_html/layouts/Default/modules/Base/resources/RecordList.js, public_html/layouts/resources/Connector.js, public_html/layouts/resources/app.js
=> Changed then to done

languages/en-US/Basic.json, layouts/Default/modules/Users/Modal/AccessActivityHistoryModal.tpl, modules/Users/View/AccessActivityHistoryModal.php
=> Added access activity history modal

languages/en-US/Users.json, layouts/Default/modules/Base/CoreLog.tpl
=> Corrected view the log card and changed translation

app/TextParser.php, app/Viewer.php, layouts/Default/modules/Users/Modal/AccessActivityHistoryModal.tpl, modules/Users/View/AccessActivityHistoryModal.php
Added truncate text for the user agent column
=> Added truncate text for the user agent column

languages/en-US/Users.json, layouts/Default/modules/Users/Login.tpl, layouts/Default/modules/Users/LoginPassResetToken.tpl, modules/Users/View/Login.php, modules/Users/View/LoginPassReset.php, public_html/layouts/resources/Login.js, public_html/layouts/resources/LoginPassReset.js
Added validation change password
=> Added validation change password

app/Layout/Action.php, public_html/layouts/Default/skins/basic/views/_List.scss
=> Corrected view the action button.

modules/Base/Model/Record.php, public_html/layouts/resources/app.js
=> Added popover in action buttons.

layouts/Default/modules/Base/Detail/DetailView.tpl, layouts/Default/modules/Base/Edit/EditView.tpl
**DETAIL VIEW:**
**BEFOR:**
**AFTER:**
**EDIT VIEW:
BEFOR:**
**AFTER:**
=> Changed the size of the description field.

layouts/Default/modules/Base/Detail/DetailView.tpl, public_html/layouts/Default/skins/basic/_Components.scss
=> Corrected view the preview record.

layouts/Default/modules/Base/Detail/Headers.tpl, public_html/layouts/Default/skins/basic/_Components.scss, public_html/layouts/Default/skins/basic/_Variables.scss
=> Corrected view the Progress bar.

layouts/Default/modules/Base/Detail/Headers.tpl, public_html/layouts/Default/skins/basic/_Components.scss, public_html/layouts/Default/skins/basic/_Variables.scss
Reconstruction of the header progress
=> Reconstruction of the header progress

layouts/Default/modules/Base/Detail/HeadersFields.tpl
Changed key name and added class to progress
=> Changed key name and added class to progress

public_html/layouts/Default/skins/basic/_Components.scss
=> Corrected view Updates

layouts/Default/modules/Base/List/ListView.tpl, public_html/layouts/Default/modules/Base/resources/ListView.js, public_html/layouts/Default/skins/basic/libraries/_Libraries.scss
=> Corrected custom filtr

layouts/Default/modules/Base/Edit/Field/Phone.tpl, modules/Base/Model/Module.php
=> Corrected phone field

layouts/Default/modules/Base/Detail/Header.tpl, public_html/layouts/Default/skins/basic/_Components.scss
Corrected view Updates and related tab
=> Corrected view Updates and related tab

layouts/Default/modules/Base/List/Field/PickList.tpl, layouts/Default/modules/Base/List/Field/String.tpl, layouts/Default/modules/Base/List/ListView.tpl, modules/Base/View/ListView.php
Added a field to the list view
=> Added a field to the list view

layouts/Default/modules/Base/Edit/Form.tpl
=> Centered action buttons.

layouts/Default/modules/Base/List/Field/PickList.tpl, layouts/Default/modules/Base/List/Field/String.tpl, layouts/Default/modules/Base/List/Field/Time.tpl
Added a field Time to the list view
=> Added a field Time to the list view

layouts/Default/modules/Base/List/Field/DateTime.tpl, layouts/Default/modules/Base/List/Field/Time.tpl, modules/Base/FieldTypes/DateTimeField.php, public_html/layouts/Default/modules/Base/resources/ListView.js
Added a field DateTime to the list view
=> Added a field DateTime to the list view

layouts/Default/modules/Base/List/Field/Date.tpl, modules/Base/FieldTypes/DateField.php
Added a field Date to the list view
=> Added a field Date to the list view

layouts/Default/modules/Base/List/Field/Boolean.tpl
Added a field Boolean to the list view
=> Added a field Boolean to the list view

layouts/Default/modules/Base/List/Field/Owner.tpl
Added a field Owner to the list view
=> Added a field Owner to the list view

public_html/layouts/Default/skins/basic/libraries/_Libraries.scss
Hidden tabdrop on missing items.
=> Hidden tabdrop on missing items.

layouts/Default/modules/Base/List/Field/Tree.tpl, public_html/layouts/Default/modules/Base/resources/ListView.js
Added a field Tree to the list view
=> Added a field Tree to the list view

layouts/Default/modules/Base/List/Field/Country.tpl
Added a field Country to the list view
=> Added a field Country to the list view

layouts/Default/modules/Base/Edit/Field/SharedOwner.tpl, layouts/Default/modules/Base/List/Field/SharedOwner.tpl, modules/Base/FieldTypes/SharedOwnerField.php, public_html/layouts/resources/Fields.js
Added a field Country to the list and Edit view
=> Added a field Country to the list and Edit view
